-- V7: Create tables for autonomous cattle minting robot
-- These tables store robot-generated cattle data, events, and mint operations

-- Robot cattle records (animals with SISBOV and metadata)
CREATE TABLE IF NOT EXISTS robot_cattle (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sisbov VARCHAR(14) NOT NULL UNIQUE, -- BR + 12 digits
    birth_date DATE NOT NULL,
    breed VARCHAR(50) NOT NULL, -- Nelore, Angus, Brahman, etc.
    gender VARCHAR(10) NOT NULL, -- Male, Female
    state VARCHAR(2) NOT NULL, -- MS, MT, SP, GO, RS
    municipality_code VARCHAR(7), -- IBGE code
    owner_hash VARCHAR(100) NOT NULL, -- hash:owner:blake3(name)
    status VARCHAR(20) NOT NULL DEFAULT 'active', -- active, sold, deceased
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Robot events (birth, vaccination, transfer, weight, movement)
CREATE TABLE IF NOT EXISTS robot_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cattle_id UUID NOT NULL REFERENCES robot_cattle(id) ON DELETE CASCADE,
    event_type VARCHAR(50) NOT NULL, -- birth, vaccination, transfer, weight, movement
    event_date DATE NOT NULL,
    from_owner_hash VARCHAR(100), -- For transfers
    to_owner_hash VARCHAR(100), -- For transfers
    vet_hash VARCHAR(100), -- For vaccinations: hash:vet:blake3(name)
    metadata JSONB, -- Event-specific data (weight_kg, vaccine_type, location, etc.)
    dfid VARCHAR(50), -- Set after successful push
    local_id UUID, -- Set after local item creation
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Robot mint operations (tracking DFID assignment and blockchain transactions)
CREATE TABLE IF NOT EXISTS robot_mints (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cattle_id UUID NOT NULL REFERENCES robot_cattle(id) ON DELETE CASCADE,
    dfid VARCHAR(50) NOT NULL,
    local_id UUID NOT NULL,
    cid VARCHAR(100), -- IPFS CID
    stellar_tx VARCHAR(100), -- Stellar transaction hash
    operation_id UUID, -- Circuit operation ID
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_robot_cattle_sisbov ON robot_cattle(sisbov);
CREATE INDEX IF NOT EXISTS idx_robot_cattle_state ON robot_cattle(state);
CREATE INDEX IF NOT EXISTS idx_robot_cattle_owner ON robot_cattle(owner_hash);
CREATE INDEX IF NOT EXISTS idx_robot_cattle_status ON robot_cattle(status);
CREATE INDEX IF NOT EXISTS idx_robot_events_cattle ON robot_events(cattle_id);
CREATE INDEX IF NOT EXISTS idx_robot_events_type ON robot_events(event_type);
CREATE INDEX IF NOT EXISTS idx_robot_events_date ON robot_events(event_date);
CREATE INDEX IF NOT EXISTS idx_robot_mints_cattle ON robot_mints(cattle_id);
CREATE INDEX IF NOT EXISTS idx_robot_mints_dfid ON robot_mints(dfid);

-- Comments for documentation
COMMENT ON TABLE robot_cattle IS 'Autonomous robot cattle records with SISBOV and hashed owner information';
COMMENT ON TABLE robot_events IS 'Cattle lifecycle events generated by robot (birth, vaccination, transfer, etc.)';
COMMENT ON TABLE robot_mints IS 'Tracking of DFID assignment and blockchain minting operations';
COMMENT ON COLUMN robot_cattle.owner_hash IS 'BLAKE3 hash of owner name/company for privacy';
COMMENT ON COLUMN robot_events.vet_hash IS 'BLAKE3 hash of veterinarian name for privacy';
