pub mod auth;
pub mod receipts;
pub mod events;
pub mod circuits;
pub mod items;
pub mod workspaces;
pub mod activities;
pub mod audit;
pub mod zk_proofs;
pub mod adapters;
pub mod storage_history;
pub mod admin;
pub mod api_keys;
pub mod user_credits;
pub mod notifications;
pub mod shared_state;
pub mod test_blockchain;

pub use auth::auth_routes;
pub use receipts::receipt_routes;
pub use events::event_routes;
pub use circuits::circuit_routes;
pub use items::item_routes;
pub use workspaces::workspace_routes;
pub use activities::activity_routes;
pub use audit::audit_routes;
pub use zk_proofs::zk_proof_routes;
pub use adapters::adapter_routes;
pub use storage_history::storage_history_routes;
pub use admin::admin_routes;
pub use api_keys::*;
pub use user_credits::routes as user_credits_routes;
pub use notifications::{notifications_rest_routes, notifications_ws_route};
pub use test_blockchain::test_blockchain_routes;